image: archlinux
packages:
- rustup
- mongodb-bin
repositories: {}
shell: false
sources:
  - https://github.com/hackagotchi/backend
tasks:
- setup: |
    rustup toolchain install nightly
    cd backend/
    rustup run nightly cargo fetch
- nightly: |
    rustup default nightly
    cd backend/
    cargo build
    sudo systemctl start mongodb
    cargo test
    cargo fmt -- --check
