image: archlinux
packages:
- rustup
repositories: {}
shell: false
sources:
  - https://git.sr.ht/~muirrum/hackagotchi-backend
tasks:
- setup: |
    rustup toolchain install stable
    cd hackagotchi-backend/
    rustup run stable cargo fetch
- stable: |
    rustup default stable
    cd hackagotchi-backend/
    cargo build
    cargo test
    cargo fmt -- --check
