image: archlinux
packages:
- rustup
- aur/mongodb-bin-4.0
repositories: {}
shell: false
sources:
  - https://github.com/hackagotchi/backend
tasks:
- setup: |
    rustup toolchain install nightly
    cd backend/
    rustup run nightly cargo fetch
- nightly: |
    rustup default nightly
    cd backend/
    export UPDATES_PER_SECOND=10000
    export SERVER_URL="https://localhost:8000"
    cargo b --bin server
    cargo r --bin server & bg
    cargo t --all-features
    cargo fmt -- --check
