image: archlinux
packages:
- rustup
repositories: {}
shell: false
sources:
- https://github.com/hackagotchi/backend
tasks:
- setup: |
    rustup toolchain install nightly stable
    cd backend/
    rustup run stable cargo fetch
- stable: |
    rustup default stable
    cd backend/
    cargo build
    cargo test
    cargo fmt -- --check
