[package]
name = "backend"
version = "0.2.0"
authors = ["Rishi Kothari <itsrishikothari@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
hcor = { path = "../hcor/" , features = [ "actix", "mongo" ] }
bson = "1.0"
serde = { version = "1.0", features = ["derive"]}
uuid = { version = "0.8.1", features = ["v4", "serde"] }
mongodb = "1.0"
derive_more = "0.99.9"
tokio = "0.2.21"
reqwest = "0.10.6"
