[package]
name = "backend"
version = "0.2.0"
authors = ["Rishi Kothari <itsrishikothari@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fll-scoring = "0.1.0"
actix-web = "2.0"
actix-rt = "1.0"
bson = "1.0"
serde = { version = "1.0", features = ["derive"]}
uuid = { version = "0.8.1", features = ["v4", "serde"] }
mongodb = "1.0"
