[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.check-format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--check"]

[tasks.build-test-server]
dependencies = [ "check-format" ]
command = "cargo"
args = ["build", "--bin", "server", "--features=autoclose"]

[tasks.run-test-server]
command = "cargo"
args = ["run", "--bin", "server", "--features=autoclose"]

[tasks.test-against-server]
command = "cargo"
args = ["test", "--all-features"]

[tasks.test]
clear = true
env = { "SERVER_URL" = "http://localhost:8000", "UPDATES_PER_SECOND" = 10000 }
dependencies = ["build-test-server"]
run_task = { name = ["run-test-server", "test-against-server"], parallel = true }

[tasks.build-config-and-test]
dependencies = [ "config" ]
env = { "CONFIG_PATH" = "./config" }
run_task = { name = ["test"], parallel = true }

[tasks.clean-hcor]
ignore_errors = true
command = "rm"
args = [ "-rf", "./hcor" ]

[tasks.clean-config]
ignore_errors = true
command = "rm"
args = [ "-rf", "./config" ]

[tasks.build-config]
command = "cargo"
args = [ "r", "--bin", "verify", "--features=config_verify" ]

[tasks.config]
script_runner = "@shell"
script = [
'''
git clone https://github.com/hackagotchi/config.git
git clone https://github.com/hackagotchi/hcor.git --branch staging
cd hcor
cargo r --bin verify --features=config_verify
export CONFIG_PATH=./config
'''
]
dependencies = [ "clean-config", "clean-hcor" ]
